### ISSUE TITLE
Support middleman v4

### ISSUE THREAD

**Issue by alem0lars** [AndrewKvalheim/middleman-pry#3]
At the moment `middleman-pry` doesn't support new middleman versions (4 and above).

Is it possible to add support ?

**Comment by AndrewKvalheim** [comment]
Yes, an [update][branch] is ready to go, pending the release of middleman/middleman#1473. You can try it via:

```ruby
gem 'middleman', github: 'AndrewKvalheim/middleman', branch: 'overridable-console-v4'
gem 'middleman-pry', github: 'AndrewKvalheim/middleman-pry', branch: 'middleman-v4'
```

but I don't plan on maintaining those branches.


  [branch]: https://github.com/AndrewKvalheim/middleman-pry/tree/middleman-v4

**Comment by tdreyno** [comment]
If there are regressions on the extension API side in v4, please log them as bugs. We don't want to break existing extensions.

**Comment by AndrewKvalheim** [comment]
No regression; this hasn't been using the extension API at all until a week ago.
