### ISSUE TITLE
'override_v4' - uninitialized constant Middleman::Cli::Console

### ISSUE THREAD

**Issue by theonlyriddle** [AndrewKvalheim/middleman-pry#4]
I'm experiencing an error when trying to access the pry console. 

When I run the command `bundle exec middleman console` I get the following error `middleman-pry-1.0.0/lib/middleman-pry/extension.rb:33:in 'override_v4': uninitialized constant Middleman::Cli::Console (NameError)`

I'm using Ruby 2.3.0 and below is my Gemfile for reference.

```
gem "bourbon", "~> 4.2"
gem "middleman", "~> 4.0"
gem "middleman-autoprefixer", "~> 2.6"
gem "middleman-deploy", "= 2.0.0.pre.alpha"
gem "middleman-livereload", "~> 3.4"
gem "middleman-pry"
gem "middleman-sprockets", "= 4.0.0.rc.1"
gem "neat", "~> 1.7"
gem "sassc", "~> 1.8"
```

Any idea how to solve this?

**Comment by AndrewKvalheim** [comment]
Thanks for the heads-up. Looks like as of Middleman 4.1.3 the [CLI backwards compatibility][compatibility] no longer [loads all CLI items][diff]. middleman-pry 1.0.1 should resolve the issue.


  [diff]: https://github.com/middleman/middleman/commit/1f3bf47#diff-71c4f5cfeb9761c9d93394d7a2a2b2e2L33
  [compatibility]: https://github.com/middleman/middleman/blob/1f3bf47/middleman-cli/lib/middleman-core/cli.rb
